### ISSUE TITLE
1주차_해시 LEVEL1 정리_190705

### ISSUE THREAD

**Issue by dltnwls0526** [hongminpark/pyrithm#1]
<요건 알고가자>
1) 리스트에서 아이템 바로 삭제: remove (remove()의 시간복잡도 n  / pop의 시간복잡도 1)
2) 리스트에서 인덱스로 삭제: pop 
3) enumerate : 리스트에서 인덱스랑 값을 같이 뱉어줌
4) set: 중복 제거
5) collections.Counter(participant) - collections.Counter(completion)하면 value 0 인 애들은 안 보임 

<찬주>
처음에 정렬을 해서 참여자랑 완주자가 전부 정렬된 상태니까 for문을 다돌고 return을 못했을 경우에만 마지막 return을 타게되는것!

<홍민>
remove() 시간복잡도 n 
(For 루프) * (remove) = > n *n의 시간복잡도  

리스트 두개를 sorting한다음(효율성 향상)에 for 루프로 한명씩 비교를 하는 것
소팅된 part=[a,b,c,c,d]
소팅된 com=[a,b,c,d] 
이러케라면 for루프를 돌려서 리스트 하나하나 값을 비교해서 중간에 값이 다른애가있으면 
고놈이 통과 못한 애인거쥐

<정아>
동명이인 없을 경우, set 함수를 통해 count 할 필요 없이 바로 return해서 효율성 향상.

<수진>
collections.Counter(participant) - collections.Counter(completion)
하면 value 0 인 애들은 안 보임 

participant = ['leo', 'kiki', 'eden', 'eden']
completion = ['leo', 'eden','kiki']
collections.Counter(participant) - collections.Counter(completion)
=> Counter({'eden': 1})

<민정>
else는 동명이인있을때만 타는건데 
if에서return값이없으면 무조건 동명이인인 사람이 완주못한사람ㅇ기때문에 동명이인을 찾아서 return해줍니다,
=> 동명이인이 리스트 내에 뒷 순서에 있으면 for 루프를 여러 번 타기 때문에 비효율적일 수 있음 . 정렬을 하는 것이 일단은 좋을 듯 

<솔미>
명이인 없으면 else 타고, 동명이인 있으면 counter 로 1개 이상인 애 내뱉음 

But, 
part, comp = ['a','a','b','b','c','c','c'], ['a','a','b','b','c','c'] 
solution(part,comp) => ['a', 'b', 'c']
동명이인 여러 개일 경우 오류! 카운터끼리 빼는 과정이 필요할 듯

**Comment by hongminpark** [comment]
리뷰 고맙습니돠
이거 닫으면 되려나 .. ;;
